### ISSUE TITLE
Calls to `wp_die()` will kill the admin if the service is unreachable or goes down.

### ISSUE THREAD

**Issue by pippercameron** [thePlatform/thePlatform-video-manager#30]
The plugin shouldn't die in a generic api call handler. This risks taking down the entire site/admin or at least parts of it if the service becomes unreachable or goes down for some reason. This doesn't need to necessarily fail silently, but it does need to fail gracefully. :)

See https://github.com/thePlatform/thePlatform-video-manager/blob/development/thePlatform-helper.php#L197

**Comment by Mataniko** [comment]
Resolved in 1.3.0
